In [129]:
s = "I like cheese cheese"
t = "like"
a = []

def checks():
    if all(s.isalpha() or s.isspace() for s in s):
        return
    
def checkt():
    if all(s.isalpha() or s.isspace() for s in s):
        return
def testlength():
    if len(t) >= 1 and len(s) >= len(t) and len(t) >= 10**6 :
            return
    else:
        exit
def strlen():
    if len(s) >=1 and len(s) <=15:
        return
    else:
        exit
def strlen1():
    if len(t) >=1 and len(t) <=15:
        return
    else:
        exit
def check(s, t):
    checks()
    checkt()
    strlen()
    strlen1()
    testlength()
    s=s.split()
    t=t.split()
    for word in s:
        if word not in t:
                a.append(word)
    print(a)
    
check(s,t)

['I', 'cheese', 'cheese']

In [19]:
import pandas as pd

In [79]:
filename = 'output.txt'
data = pd.read_csv(filename, sep=" ", header=None)

data.columns = ["hostname", "col2", "col3", "timestamp", "timezone", "request", "request2", "response code", "total_bytes"]
data['time'] = data[['timestamp', 'timezone']].apply(lambda x: ''.join(x), axis=1)
data

,hostname,col2,col3,timestamp,timezone,request,request2,response code,total_bytes,time
0,Host1,-,-,[09/11/2018:03:15:22,-0400],“GET/images/NASA-logosmail.gif,HTTP/1.0”,200,3756,[09/11/2018:03:15:22-0400]
1,Host1,-,-,[10/11/2018:15:12:45,-0400],“GET/images/pic1.gif,HTTP/1.0”,500,100,[10/11/2018:15:12:45-0400]
2,Host2,-,-,[10/11/2018:17:34:35,-0400],“GET/images/pic2.gif,HTTP/1.0”,200,56789,[10/11/2018:17:34:35-0400]
3,Host2,-,-,[10/11/2018:21:56:07,-0400],“GET/images/pic3.gif,HTTP/1.0”,200,76543,[10/11/2018:21:56:07-0400]
4,Host3,-,-,[11/11/2018:01:17:48,-0400],“GET/images/pic1.gif,HTTP/1.0”,200,81947,[11/11/2018:01:17:48-0400]
5,Host4,-,-,[12/11/2018:07:33:21,-0400],“GET/images/pic1.gif,HTTP/1.0”,200,81947,[12/11/2018:07:33:21-0400]
6,Host4,-,-,[12/11/2018:19:51:39,-0400],“GET/images/NASA-logosmail.gif,HTTP/1.0”,200,3756,[12/11/2018:19:51:39-0400]

In [80]:
host_count = data.groupby('hostname')['hostname'].count()
host_count

hostname
Host1    2
Host2    2
Host3    1
Host4    2
Name: hostname, dtype: int64

In [81]:
host_count.to_csv('record_'+filename, sep=' ', mode='a')

In [92]:
arr = [1,2,3,4,5, 100000000000]
def findNumber(arr, k):
    if arr <1 or arr > 10**9:
        print('NO')
    if k <= 1 or k >= 10**5:
        print('No')
    elif k in arr:
        print('YES')
    else:
        print('NO')

findNumber(arr, 5)

TypeError: '<' not supported between instances of 'list' and 'int'

In [ ]:
def checks():
    if all(s.isalpha() or s.isspace() for s in s):
        return
    
def checkt():
    if all(s.isalpha() or s.isspace() for s in s):
        return
def testlength():
    if len(t) >= 1 and len(s) >= 1:
        if len(t) < len(s):
            return

def check(s, t):
    checks()
    checkt()
    testlength()
    s=s.split()
    t=t.split()
    for word in s:
        if word not in t:
            a.append(word)
    print(a)
    
check(s,t)